plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-md

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
